version: "3"
services:
  web:
    build: ./web
    volumes:
      - ./web/public:/usr/share/nginx/public
    ports:
      - "${PORT}:80"

  app:
    build:
      context: ./app
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    volumes:
      - ./app/src:/app